/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventIdUploadRouteImport } from './routes/event.$id.upload'
import { Route as EventIdTvRouteImport } from './routes/event.$id.tv'
import { Route as EventIdAfterfestRouteImport } from './routes/event.$id.afterfest'
import { Route as AuthenticatedEventIdAdminRouteImport } from './routes/_authenticated/event.$id.admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdUploadRoute = EventIdUploadRouteImport.update({
  id: '/event/$id/upload',
  path: '/event/$id/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdTvRoute = EventIdTvRouteImport.update({
  id: '/event/$id/tv',
  path: '/event/$id/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdAfterfestRoute = EventIdAfterfestRouteImport.update({
  id: '/event/$id/afterfest',
  path: '/event/$id/afterfest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventIdAdminRoute =
  AuthenticatedEventIdAdminRouteImport.update({
    id: '/event/$id/admin',
    path: '/event/$id/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/event/$id/afterfest': typeof EventIdAfterfestRoute
  '/event/$id/tv': typeof EventIdTvRoute
  '/event/$id/upload': typeof EventIdUploadRoute
  '/event/$id/admin': typeof AuthenticatedEventIdAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/event/$id/afterfest': typeof EventIdAfterfestRoute
  '/event/$id/tv': typeof EventIdTvRoute
  '/event/$id/upload': typeof EventIdUploadRoute
  '/event/$id/admin': typeof AuthenticatedEventIdAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/event/$id/afterfest': typeof EventIdAfterfestRoute
  '/event/$id/tv': typeof EventIdTvRoute
  '/event/$id/upload': typeof EventIdUploadRoute
  '/_authenticated/event/$id/admin': typeof AuthenticatedEventIdAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/event/$id/afterfest'
    | '/event/$id/tv'
    | '/event/$id/upload'
    | '/event/$id/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/event/$id/afterfest'
    | '/event/$id/tv'
    | '/event/$id/upload'
    | '/event/$id/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/event/$id/afterfest'
    | '/event/$id/tv'
    | '/event/$id/upload'
    | '/_authenticated/event/$id/admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EventIdAfterfestRoute: typeof EventIdAfterfestRoute
  EventIdTvRoute: typeof EventIdTvRoute
  EventIdUploadRoute: typeof EventIdUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/upload': {
      id: '/event/$id/upload'
      path: '/event/$id/upload'
      fullPath: '/event/$id/upload'
      preLoaderRoute: typeof EventIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/tv': {
      id: '/event/$id/tv'
      path: '/event/$id/tv'
      fullPath: '/event/$id/tv'
      preLoaderRoute: typeof EventIdTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/afterfest': {
      id: '/event/$id/afterfest'
      path: '/event/$id/afterfest'
      fullPath: '/event/$id/afterfest'
      preLoaderRoute: typeof EventIdAfterfestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/event/$id/admin': {
      id: '/_authenticated/event/$id/admin'
      path: '/event/$id/admin'
      fullPath: '/event/$id/admin'
      preLoaderRoute: typeof AuthenticatedEventIdAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEventIdAdminRoute: typeof AuthenticatedEventIdAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEventIdAdminRoute: AuthenticatedEventIdAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EventIdAfterfestRoute: EventIdAfterfestRoute,
  EventIdTvRoute: EventIdTvRoute,
  EventIdUploadRoute: EventIdUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
